"""change table

Revision ID: f4bc4cf9268b
Revises: 59ee5671be03
Create Date: 2023-10-29 19:07:13.821131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f4bc4cf9268b'
down_revision: Union[str, None] = '59ee5671be03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('USERS2')
    op.add_column('users', sa.Column('UserId', postgresql.UUID(), nullable=True))
    op.add_column('users', sa.Column('Login', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('Email', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('Password', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('Name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('Activated', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('Roles', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('Status', sa.String(length=100), nullable=True))
    op.drop_column('users', 'email')
    op.drop_column('users', 'status')
    op.drop_column('users', 'mediumPictureUrl')
    op.drop_column('users', 'skype')
    op.drop_column('users', 'settings')
    op.drop_column('users', 'info')
    op.drop_column('users', 'location')
    op.drop_column('users', 'rating')
    op.drop_column('users', 'online')
    op.drop_column('users', 'registration')
    op.drop_column('users', 'login')
    op.drop_column('users', 'originalPictureUrl')
    op.drop_column('users', 'smallPictureUrl')
    op.drop_column('users', 'icq')
    op.drop_column('users', 'password')
    op.drop_column('users', 'id')
    op.drop_column('users', 'roles')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('roles', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('users', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('icq', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('smallPictureUrl', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('originalPictureUrl', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('login', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('registration', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('online', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('rating', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('info', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('settings', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('skype', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('mediumPictureUrl', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'Status')
    op.drop_column('users', 'Roles')
    op.drop_column('users', 'Activated')
    op.drop_column('users', 'Name')
    op.drop_column('users', 'Password')
    op.drop_column('users', 'Email')
    op.drop_column('users', 'Login')
    op.drop_column('users', 'UserId')
    op.create_table('USERS2',
    sa.Column('UserId', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('Login', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('Email', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('Password', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('Name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('Activated', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('UserId', name='USERS2_pkey')
    )
    # ### end Alembic commands ###
